In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]


Instructions for updating:
Use the retry module or similar alternatives.


In [2]:
'''
one cell RNN
input: dim=4
output: dim=hidden_size=2 <== 이건 내 마음대로 조절 가능
'''

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval()) #이 결과값은 2개 --> hidden_size=2이기 때문에

array([[[ 0.02698182, -0.04452245]]], dtype=float32)


In [4]:
'''
one cell RNN
input: dim=4
output: dim=hidden_size=2 <== 이건 내 마음대로 조절 가능
sequence=5
'''
with tf.variable_scope('two_cell_ex') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print("x_data.shape:", x_data.shape)
    pp.pprint(x_data)

    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

x_data.shape: (1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[-0.00265575, -0.06229455],
        [-0.05157711,  0.09736399],
        [-0.06478827,  0.00848961],
        [-0.07013734, -0.06960533],
        [ 0.15272294,  0.03199625]]], dtype=float32)
